blank_issues_enabled: true
contact_links:
  - name: I have a question / I need help
    url: https://github.com/visgl/deck.gl-community/discussions
    about: Please ask generic questions or request help in discussions. Non-specific issues will be closed by maintainers.
